export type Language = 'zh' | 'en';
export const english: Record<string, string> = {
  '章节': 'CHAPTER', '为你留一点空间': 'A LITTLE ROOM FOR YOU',
  '只在你我之间': 'JUST BETWEEN US', '少一点喧闹，多一点陪伴。': 'LESS NOISE. MORE PRESENCE.',
  '交互界面设计样例': 'A WORKING INTERFACE STUDY', '值得收好的小事': 'LITTLE THINGS TO KEEP',
  '一个新的开始': 'A FRESH START',
  '小满': 'Maya', '满': 'M', '陆屿': 'Leo', '屿': 'L',
  '写点字，也听你说。': 'A few words. A little space to be heard.',
  '慢热的倾听者': 'A thoughtful listener', '喜欢海边': 'At home by the sea',
  '海边的咖啡馆': 'A café by the sea',
  '那就先把那些‘应该做的事’放一放。窗外的海还在，咖啡也可以慢慢喝。\n\n今天有没有一个很小的瞬间，让你觉得还不错？': 'Then let the things you “should” be doing wait a little. The sea is still there, and there’s no rush to finish your coffee.\n\nWas there one small moment today that felt good?',
  '今天有点累，什么都不想做。': 'I’m tired today. I don’t feel like doing anything.',
  '走一小段路，聊一点日常。': 'A short walk. An ordinary conversation.',
  '温和的同行者': 'Easy company', '收集旧唱片': 'Collects old records',
  '雨后的林间小屋': 'A woodland cabin after the rain',
  '那今晚就走慢一点吧。刚才雨停了，树叶上还挂着水珠。\n\n不必把一天都解释清楚，挑一件想说的小事就好。': 'Let’s take it slowly tonight. The rain has just stopped, and there are still drops on the leaves.\n\nYou don’t have to explain your whole day. Start with one little thing, if you like.',
  '想找个安静的地方待一会儿。': 'I’d like somewhere quiet to sit for a while.',
  '说说今天的小事': 'One small thing', '陪我安静一会儿': 'A quiet moment', '换个轻松的话题': 'Something lighter',
  '好，我们从一件小事说起。\n\n比如路上看到的一棵树，或者午饭里最好吃的那一口。你想先说哪件？': 'Let’s start small.\n\nA tree you passed on your way home, or the best bite of lunch. What comes to mind?',
  '好，那就不用急着找话题。\n\n把肩膀放松一点，看看窗外。等你想说的时候，再写下来就好。': 'There’s no need to find something to say.\n\nLet your shoulders relax. Look out of the window. Write whenever you feel like it.',
  '那来聊个轻松的：如果明天可以随意去一个地方，你会选山里、海边，还是熟悉的小街？': 'Something lighter, then: if you could go anywhere tomorrow, would it be the mountains, the sea, or a familiar little street?',
  '这里先展示一段预设回应，方便你体验聊天的节奏与排版。\n\n如果想继续试试，可以点下方的话题，或者切换右上角的‘入境’，看看另一种阅读氛围。': 'This is a preset reply, so you can try the pace and layout of a conversation.\n\nChoose a topic below, or switch to “Afterglow” in the top right to try a different atmosphere.',
  '已取消收藏': 'Removed from Keepsakes', '收进我们的片段了': 'Added to Keepsakes',
  '浏览器暂时无法播放环境声，请检查声音权限': 'Ambient sound is unavailable. Check your browser’s audio permissions.',
  '关闭导航': 'Close navigation', 'STILL 首页': 'STILL home', '慢一点，听你说': 'A little room to be heard',
  '留一点时间，给自己': 'A MOMENT FOR YOURSELF', '此刻的对话': 'Our conversation',
  '我们的片段': 'Keepsakes', '熟悉的声音': 'FAMILIAR VOICES',
  '海边的咖啡还温着': 'The coffee is still warm', '下过雨的路，很好走': 'A walk after the rain',
  '不用每一天': 'Not every day', '都过得很有意义。': 'needs to mean something.',
  '有些时候，待着就很好。': 'Sometimes, just being here is enough.',
  '你': 'Y', '这一刻的你': 'Here, as you are', '把今天放轻一点': 'Let the day feel lighter',
  '关于这个演示': 'About this demo', '展开导航': 'Open navigation', '此刻': 'Now',
  '与': 'With ', '的对话': '', '聊天布局': 'Conversation atmosphere',
  '留白': 'Daylight', '入境': 'Afterglow', '交互样例': 'Live demo',
  '此刻，慢慢来': 'Take your time', '聊天': 'Conversation',
  '今天，想从哪里聊起？': 'Where shall we begin?',
  '重新开始这段对话': 'Start this conversation again', '今天 · 傍晚': 'Today · Early evening',
  '窗外的天色慢慢暗下来，杯子里还有一点温热。': 'The light outside is fading. There’s still a little warmth in your cup.',
  '雨刚刚停。远处传来一声鸟鸣，唱片还在转。': 'The rain has stopped. A bird calls in the distance. The record keeps turning.',
  '演示对话': 'Sample dialogue', '取消收藏这段话': 'Remove this passage from Keepsakes',
  '收藏这段话': 'Save this passage', '已收好': 'Saved', '收好这句话': 'Keep these words',
  '演示回应准备中': 'Preparing a sample reply', '回到最新': 'Back to the latest',
  '也可以这样开始': 'OR START HERE', '写给': 'Write to ', '的话': '',
  '不用想好再说，想到什么就写下来…': 'No need to find the right words. Just start…',
  '环境声已开启': 'Ambient sound on', '一点环境声': 'A little ambience',
  'Enter 发送': 'Enter to send', '发送消息': 'Send message',
  '预设回复的交互演示 · 对话与收藏仅保留在本次页面': 'Preset replies · Chats and keepsakes last only for this page session',
  '关于这个样例': 'About this demo', '关闭窗口': 'Close dialog',
  '让对话，慢一点。': 'A slower kind of conversation.',
  'STILL 是一份可操作的聊天界面样例。这里的人物和对话都是演示内容，发送后会展示预设回应。': 'STILL is an interactive chat interface demo. The characters and conversations are fictional, and messages receive preset replies.',
  '你可以切换「留白 / 入境」、体验两位角色的对话、收藏片段，或打开一段轻柔的环境声。手机和桌面有各自的布局。': 'Try Daylight or Afterglow, chat with either character, save a passage, or turn on a little ambient sound. The layout adapts to desktop and mobile.',
  '对话不会上传，也不会跨设备同步。关闭或刷新页面后，输入内容与收藏都会清空。': 'Your messages stay on this page. They aren’t uploaded or synced. Refreshing or closing the page clears your conversations and keepsakes.',
  '原创界面演示 · Prayer · 2026': 'Interface study · Prayer · 2026',
  '有些话，值得再读一次。': 'Some words are worth coming back to.',
  '点对话下方的「收好这句话」，就会出现在这里。': 'Choose “Keep these words” beneath a reply to save it here.',
  '移除': 'Remove', '重新开始这段对话？': 'Start this conversation again?',
  '的消息会恢复为最初的演示内容，已经收藏的片段会保留。': ', your conversation will return to the sample dialogue. Your keepsakes will stay.',
  '继续聊': 'Keep chatting', '重新开始': 'Start again'
};
